@startuml

title __FS's Class Diagram__\n

  namespace com.fresno.fs {
    interface com.fresno.fs.Visitor {
        {abstract} + visit()
    }
  }
  

  namespace com.fresno.fs {
    interface com.fresno.fs.Builder {
        {abstract} + cdAction()
        {abstract} + createAction()
        {abstract} + delAction()
        {abstract} + exit()
        {abstract} + getRoot()
        {abstract} + lsAction()
        {abstract} + makeDirAction()
        {abstract} + sizeAction()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.DelVisitor {
        {static} - delAction : Action
        {static} + getInstance()
        + visit()
        - DelAction()
        - delRecursive()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.DeleteProxy {
        {static} - deleteProxy : DeleteProxy
        + delete()
        {static} + getInstance()
        - DeleteProxy()
        - deleteHelper()
    }
  }
  

  namespace com.fresno.fs {
    interface com.fresno.fs.FSConstant {
        {static} + ROOT_NAME : String
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.FSUtils {
        {static} + getAbsolutePath()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.FileSystemBuilder {
        {static} - builder : Builder
        + cdAction()
        + createAction()
        + delAction()
        + exit()
        {static} + getInstance()
        + getRoot()
        + lsAction()
        + makeDirAction()
        + sizeAction()
        - FileSystemBuilder()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.FileSystemClient {
        {static} + main()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.FileSystemDisplay {
        {static} - fileSystemDisplay : FileSystemDisplay
        {static} + getInstance()
        + printFileSystem()
        - FileSystemDisplay()
        {static} - printHelper()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.FooterTextDisplay {
        + FooterTextDisplay()
        + display()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.HeaderTextDisplay {
        + HeaderTextDisplay()
        + display()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.LsVisitor {
        {static} - lsAction : Action
        {static} + getInstance()
        + visit()
        - LsAction()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.Node {
        ~ children : Map<String, Node>
        ~ depth : int
        ~ fileSize : int
        ~ isFile : boolean
        ~ name : String
        ~ toBeDeleted : boolean
        + Node()
        + Node()
        + Node()
        + accept()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.SizeVisitor {
        {static} - sizeAction : Action
        {static} + getInstance()
        + visit()
        - SizeAction()
        - getSize()
    }
  }
  

  namespace com.fresno.fs {
    interface com.fresno.fs.TreeDisplay {
        {abstract} + display()
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.TreeDisplayAdapter {
        + TreeDisplayAdapter()
        + display()
    }
  }
  

  com.fresno.fs.DelVisitor .up.|> com.fresno.fs.Visitor
  com.fresno.fs.FileSystemBuilder .up.|> com.fresno.fs.Builder
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.Node : curNode
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.Visitor : del
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.DeleteProxy : deleteProxy
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.Visitor : ls
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.Node : root
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.Visitor : size
  com.fresno.fs.FooterTextDisplay -up-|> com.fresno.fs.HeaderTextDisplay
  com.fresno.fs.HeaderTextDisplay .up.|> com.fresno.fs.TreeDisplay
  com.fresno.fs.HeaderTextDisplay o-- com.fresno.fs.TreeDisplay : treeDisplay
  com.fresno.fs.LsVisitor .up.|> com.fresno.fs.Visitor
  com.fresno.fs.Node o-- com.fresno.fs.Node : parent
  com.fresno.fs.SizeVisitor .up.|> com.fresno.fs.Visitor
  com.fresno.fs.TreeDisplayAdapter .up.|> com.fresno.fs.TreeDisplay
  com.fresno.fs.TreeDisplayAdapter o-- com.fresno.fs.FileSystemDisplay : fsDisplay


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
