@startuml

title __ASSIGNMENT's Class Diagram__\n

  namespace com.fresno.fs {
    interface com.fresno.fs.Action {
    }
  }
  

  namespace com.fresno.fs {
    interface com.fresno.fs.Builder {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.DelAction {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.DeleteProxy {
    }
  }
  

  namespace com.fresno.fs {
    interface com.fresno.fs.FSConstant {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.FSUtils {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.FileSystemBuilder {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.FileSystemClient {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.FileSystemDisplay {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.FooterTextDisplay {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.HeaderTextDisplay {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.LsAction {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.Node {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.SizeAction {
    }
  }
  

  namespace com.fresno.fs {
    interface com.fresno.fs.TreeDisplay {
    }
  }
  

  namespace com.fresno.fs {
    class com.fresno.fs.TreeDisplayAdapter {
    }
  }
  

  com.fresno.fs.DelAction .up.|> com.fresno.fs.Action
  com.fresno.fs.FileSystemBuilder .up.|> com.fresno.fs.Builder
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.Node : curNode
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.Action : del
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.DeleteProxy : deleteProxy
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.Action : ls
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.Node : root
  com.fresno.fs.FileSystemBuilder o-- com.fresno.fs.Action : size
  com.fresno.fs.FooterTextDisplay -up-|> com.fresno.fs.HeaderTextDisplay
  com.fresno.fs.HeaderTextDisplay .up.|> com.fresno.fs.TreeDisplay
  com.fresno.fs.HeaderTextDisplay o-- com.fresno.fs.TreeDisplay : treeDisplay
  com.fresno.fs.LsAction .up.|> com.fresno.fs.Action
  com.fresno.fs.Node o-- com.fresno.fs.Node : parent
  com.fresno.fs.SizeAction .up.|> com.fresno.fs.Action
  com.fresno.fs.TreeDisplayAdapter .up.|> com.fresno.fs.TreeDisplay
  com.fresno.fs.TreeDisplayAdapter o-- com.fresno.fs.FileSystemDisplay : fsDisplay


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
